### PR TITLE
Randomize questions

### PR DESCRIPTION
**Pull request by kaushikcfd**

### CODE REVIEW

**Comment by inducer** [comment]
Thanks for working on this. I feel that it is headed in a good direction.

Some comments:

* Could you add to the description some updated instructions on the required ballet of "Submit for feedback", answer question, increment `problem_version`, submit again, solve problem, submit again?
* We have to make sure that, despite randomization, we generate a solvable problem every time. Just now, for problem 3 I got this graph:

bildschirmfoto von 2018-07-11 16-43-55

I don't think that's solvable.

* Additionally, making the figures bigger should be an easy usability win. `plt.figure(figsize=(12,12))` maybe.

**Comment by inducer** [comment]
I find problem 3 unsolvable. Have you tried?

**Comment by inducer** [comment]
I'll merge this--let's do the rest of this evolution on master.

**Comment by kaushikcfd** [comment]
Is it regarding the large size of the plots?

**Comment by inducer** [comment]
No, there are plenty of pixels in the plot:

bildschirmfoto von 2018-07-12 18-09-45

It's just that the tolerance (0.1) seems to assume that the small-scale grid is usable, which i find to not be the case. Suggestion:

* Kill the small-scale grid
* Loosen the tolerance to 0.5

**Comment by kaushikcfd** [comment]
Done!

**Pull request merged**
